# -*- coding: utf-8 -*-
"""LogiSense AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQYqmqvx7QPpevgSE1ogGdNfAiXSV-eK
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="LogiSense AI", layout="wide")
st.title("🚚 LogiSense AI — Analítica Logística")

# 1. Componente para subir el archivo (Excel o CSV)
archivo_subido = st.file_uploader(
    "📁 Carga tu archivo de datos (Excel .xlsx o CSV)",
    type=["xlsx", "csv"]
)

CONFIG_HOJAS = {
    'ENERO': 430,
    'FEBRERO': 408,
    'MARZO': 370,
    'ABRIL': 662,
    'MAYO': 394,
    'JUNIO': 398,
    'JULIO': 387
}

@st.cache_data
def procesar_archivo(file):
    lista_dfs = []

    # Si es un archivo Excel con múltiples pestañas
    if file.name.endswith('.xlsx'):
        excel_file = pd.ExcelFile(file)

        for nombre_hoja, limite_fila in CONFIG_HOJAS.items():
            if nombre_hoja in excel_file.sheet_names:
                # Leer la hoja específica
                df_temp = pd.read_excel(excel_file, sheet_name=nombre_hoja, nrows=limite_fila)

                if not df_temp.empty:
                    # Limpiar nombres de columnas
                    df_temp.columns = [str(h).strip() for h in df_temp.columns]
                    df_temp['MES_ORIGEN'] = nombre_hoja
                    lista_dfs.append(df_temp)
    else:
        # Si es un archivo CSV único
        df_temp = pd.read_csv(file)
        df_temp.columns = [str(h).strip() for h in df_temp.columns]
        lista_dfs.append(df_temp)

    if not lista_dfs:
        return pd.DataFrame()

    df_out = pd.concat(lista_dfs, ignore_index=True)

    # 2. Asignar la semana
    col_sem = 'SEMANA CALENDARIO FACTURA' if 'SEMANA CALENDARIO FACTURA' in df_out.columns else 'SEMANA CALENDARIO PEDIDO'
    if col_sem in df_out.columns:
        df_out['SEMANA_ANALISIS'] = pd.to_numeric(df_out[col_sem], errors='coerce')

    # 3. Limpieza de montos financieros y volumétricos (TU LÓGICA)
    cols_a_limpiar = [
        'IMPORTE FACTURADO SIN IVA', 'KG MOVIDOS', 'FLETE FACTURA',
        'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS',
        'TOTAL FLETE', 'KM RECORRIDOS', 'TARIMAS TOTALES POR VIAJE',
        'COSTO POR TARIMA'
    ]

    for c in cols_a_limpiar:
        if c in df_out.columns:
            df_out[c] = df_out[c].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()
            df_out[c] = pd.to_numeric(df_out[c], errors='coerce').fillna(0)

    return df_out

# Carga y procesamiento del archivo
if archivo_subido is not None:
    with st.spinner("⏳ Procesando datos del archivo..."):
        df = procesar_archivo(archivo_subido)

    if not df.empty:
        st.success("✅ Base de datos cargada y validada correctamente.")

        # ---------------------------------------------------------
        # INTERFAZ CON TUS FUNCIONES Y ANÁLISIS
        # ---------------------------------------------------------
        semanas = sorted([int(x) for x in df['SEMANA_ANALISIS'].dropna().unique()])
        col1, col2 = st.sidebar.columns(2)
        sem_a = col1.selectbox("Semana A", semanas, index=0)
        sem_b = col2.selectbox("Semana B", semanas, index=min(1, len(semanas)-1))

        tab1, tab2, tab3, tab4 = st.tabs(["📊 Comparativo", "🚨 Auditoría", "📝 Prompt IA", "💬 Chat"])

        # TAB 1: Comparativo final
        with tab1:
            df_a = df[df['SEMANA_ANALISIS'] == sem_a]
            df_b = df[df['SEMANA_ANALISIS'] == sem_b]
            conceptos = ['FLETE FACTURA', 'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS', 'TOTAL FLETE']

            filas = []
            for conc in conceptos:
                m_a = df_a[conc].sum() if conc in df_a.columns else 0
                m_b = df_b[conc].sum() if conc in df_b.columns else 0
                dif = m_b - m_a
                pct = ((m_b - m_a) / m_a * 100) if m_a > 0 else 0

                filas.append({
                    'Línea de Gasto': conc,
                    f'Semana {sem_a}': f"${m_a:,.2f}",
                    f'Semana {sem_b}': f"${m_b:,.2f}",
                    'Diferencia ($)': f"${dif:,.2f}",
                    'Variación (%)': f"{pct:+.1f}%"
                })
            st.table(pd.DataFrame(filas))

        # TAB 2: Auditoría profunda
        with tab2:
            media_total_a = df[df['SEMANA_ANALISIS'] == sem_a]['TOTAL FLETE'].mean() if len(df_a) > 0 else 0
            viajes_altos = df_b[df_b['TOTAL FLETE'] > media_total_a].copy() if len(df_b) > 0 else pd.DataFrame()

            if not viajes_altos.empty:
                viajes_altos['Diferencia vs Media A'] = viajes_altos['TOTAL FLETE'] - media_total_a
                viajes_altos = viajes_altos.sort_values(by='TOTAL FLETE', ascending=False)
                st.warning(f"🚨 Auditoría: {len(viajes_altos)} viajes en la Semana {sem_b} superan la media de la Semana {sem_a}")
                cols_detalle = ['MES_ORIGEN', 'CLIENTE', 'TRANSPORTISTA', 'CIUDAD DESTINO', 'FLETE FACTURA', 'DEMORAS Y ESTADIAS', 'TOTAL FLETE', 'Diferencia vs Media A']
                cols_existentes = [c for c in cols_detalle if c in viajes_altos.columns]
                st.dataframe(viajes_altos[cols_existentes].head(10))

        # TAB 3: Generador de Prompt IA
        with tab3:
            tot_a = df_a['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_a.columns else 0
            tot_b = df_b['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_b.columns else 0
            var_tot = ((tot_b - tot_a) / tot_a * 100) if tot_a > 0 else 0
            media_a = df_a['TOTAL FLETE'].mean() if len(df_a) > 0 else 0

            prompt_texto = f"""Actúa como un Gerente Senior de Logística y Cadena de Suministro.
Analiza la siguiente variación semanal de fletes e imprevistos financieros y genera un reporte ejecutivo.

DATOS COMPARATIVOS:
- Periodo Base: Semana {sem_a} | Gasto Total: ${tot_a:,.2f} | Costo Promedio por Viaje: ${media_a:,.2f}
- Periodo Actual: Semana {sem_b} | Gasto Total: ${tot_b:,.2f}
- Variación del Gasto Total: {var_tot:+.2f}%

ESTRUCTURA DEL REPORTE SOLICITADA:
1. 📌 Resumen Ejecutivo
2. 🚨 Alertas Operativas
3. 💡 Recomendaciones de Negocio"""
            st.code(prompt_texto)

        # TAB 4: Simulación del Chat
        with tab4:
            pregunta = st.text_input("Haz una pregunta sobre tus fletes:")
            if pregunta:
                query = pregunta.lower()
                if "tarima" in query:
                    if 'COSTO POR TARIMA' in df.columns and 'TRANSPORTISTA' in df.columns:
                        agrupado = df.groupby('TRANSPORTISTA')['COSTO POR TARIMA'].mean()
                        st.success(f"🚛 Transportista con costo por tarima más alto: **{agrupado.idxmax()}** con **${agrupado.max():,.2f}** por tarima.")
                elif "demora" in query:
                    if 'DEMORAS Y ESTADIAS' in df.columns:
                        df_demoras = df[df['DEMORAS Y ESTADIAS'] > 0]
                        st.warning(f"🚨 **{len(df_demoras)} viajes** registraron demoras/estadías, sumando **${df_demoras['DEMORAS Y ESTADIAS'].sum():,.2f}**.")
                elif "viaje" in query:
                    st.info(f"📊 **{len(df)} viajes totales** con gasto acumulado de **${df['TOTAL FLETE'].sum():,.2f}**.")
else:
    st.info("👆 Por favor sube tu archivo Excel o CSV para comenzar el análisis.")