# -*- coding: utf-8 -*-
"""LogiSense AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQYqmqvx7QPpevgSE1ogGdNfAiXSV-eK
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="LogiSense AI", layout="wide")
st.title("🚚 LogiSense AI — Analítica Logística Avanzada")

# 1. Componente para subir el archivo (Excel o CSV)
archivo_subido = st.file_uploader(
    "📁 Carga tu archivo de datos (Excel .xlsx o CSV)",
    type=["xlsx", "csv"]
)

CONFIG_HOJAS = {
    'ENERO': 430,
    'FEBRERO': 408,
    'MARZO': 370,
    'ABRIL': 662,
    'MAYO': 394,
    'JUNIO': 398,
    'JULIO': 387
}

@st.cache_data
def procesar_archivo(file):
    lista_dfs = []

    # Si es un archivo Excel con múltiples pestañas
    if file.name.endswith('.xlsx'):
        excel_file = pd.ExcelFile(file)

        for nombre_hoja, limite_fila in CONFIG_HOJAS.items():
            if nombre_hoja in excel_file.sheet_names:
                # header=0 garantiza que la fila 1 del Excel sea tomada como encabezados
                df_temp = pd.read_excel(excel_file, sheet_name=nombre_hoja, nrows=limite_fila, header=0)
                if not df_temp.empty:
                    df_temp.columns = [str(h).strip() for h in df_temp.columns]
                    df_temp['MES_ORIGEN'] = nombre_hoja
                    lista_dfs.append(df_temp)
    else:
        # Si es un archivo CSV único
        df_temp = pd.read_csv(file, header=0)
        df_temp.columns = [str(h).strip() for h in df_temp.columns]
        lista_dfs.append(df_temp)

    if not lista_dfs:
        return pd.DataFrame()

    df_out = pd.concat(lista_dfs, ignore_index=True)

    # Asignar la semana
    col_sem = 'SEMANA CALENDARIO FACTURA' if 'SEMANA CALENDARIO FACTURA' in df_out.columns else 'SEMANA CALENDARIO PEDIDO'
    if col_sem in df_out.columns:
        df_out['SEMANA_ANALISIS'] = pd.to_numeric(df_out[col_sem], errors='coerce')

    # Garantizar columna de Mes para análisis mensual
    if 'MES FACTURA' not in df_out.columns:
        df_out['MES FACTURA'] = df_out['MES_ORIGEN']

    # Limpieza de montos financieros y volumétricos
    cols_a_limpiar = [
        'IMPORTE FACTURADO SIN IVA', 'KG MOVIDOS', 'FLETE FACTURA',
        'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS',
        'TOTAL FLETE', 'KM RECORRIDOS', 'TARIMAS TOTALES POR VIAJE',
        'COSTO POR TARIMA'
    ]

    for c in cols_a_limpiar:
        if c in df_out.columns:
            df_out[c] = df_out[c].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()
            df_out[c] = pd.to_numeric(df_out[c], errors='coerce').fillna(0)

    # Calcular costo por tarima si no viene directo
    if 'COSTO POR TARIMA' not in df_out.columns or (df_out['COSTO POR TARIMA'] == 0).all():
        df_out['COSTO POR TARIMA'] = np.where(
            df_out['TARIMAS TOTALES POR VIAJE'] > 0,
            df_out['TOTAL FLETE'] / df_out['TARIMAS TOTALES POR VIAJE'],
            0
        )

    return df_out

# Carga y procesamiento del archivo
if archivo_subido is not None:
    with st.spinner("⏳ Procesando datos del archivo..."):
        df_raw = procesar_archivo(archivo_subido)

    if not df_raw.empty:
        st.success("✅ Base de datos cargada y validada correctamente.")

        # ---------------------------------------------------------
        # BARRA LATERAL: FILTROS DE ANÁLISIS
        # ---------------------------------------------------------
        st.sidebar.header("🔍 Filtros Operativos")

        # 1. Filtro por Tipo de Embarque (Columna B)
        col_embarque = 'TIPO DE EMBARQUE'
        opciones_embarque = ["Todos"] + sorted([str(x) for x in df_raw[col_embarque].dropna().unique()]) if col_embarque in df_raw.columns else ["Todos"]
        embarque_sel = st.sidebar.selectbox("Tipo de Embarque (TR1, TR2, etc.)", opciones_embarque)

        # 2. Filtro por Cliente (Columna AB)
        col_cliente = 'CLIENTE'
        opciones_cliente = sorted([str(x) for x in df_raw[col_cliente].dropna().unique()]) if col_cliente in df_raw.columns else []
        clientes_sel = st.sidebar.multiselect("Cliente(s)", opciones_cliente, default=[])

        # 3. Filtro por Transportista (Columna AN)
        col_transp = 'TRANSPORTISTA'
        opciones_transp = sorted([str(x) for x in df_raw[col_transp].dropna().unique()]) if col_transp in df_raw.columns else []
        transp_sel = st.sidebar.multiselect("Transportista(s)", opciones_transp, default=[])

        # 4. Filtro por Tipo de Transporte (Columna AT)
        col_tipo_trans = 'TIPO DE TRANSPORTE'
        opciones_tipo_trans = ["Todos"] + sorted([str(x) for x in df_raw[col_tipo_trans].dropna().unique()]) if col_tipo_trans in df_raw.columns else ["Todos"]
        tipo_trans_sel = st.sidebar.selectbox("Tipo de Transporte", opciones_tipo_trans)

        # Aplicar filtros a la base de datos
        df = df_raw.copy()
        if embarque_sel != "Todos" and col_embarque in df.columns:
            df = df[df[col_embarque].astype(str) == embarque_sel]
        if clientes_sel and col_cliente in df.columns:
            df = df[df[col_cliente].astype(str).isin(clientes_sel)]
        if transp_sel and col_transp in df.columns:
            df = df[df[col_transp].astype(str).isin(transp_sel)]
        if tipo_trans_sel != "Todos" and col_tipo_trans in df.columns:
            df = df[df[col_tipo_trans].astype(str) == tipo_trans_sel]

        # ---------------------------------------------------------
        # SELECCIÓN DE PERIODO (SEMANA vs MES)
        # ---------------------------------------------------------
        st.sidebar.markdown("---")
        st.sidebar.header("📅 Periodos de Comparación")
        modo_periodo = st.sidebar.radio("Comparar por:", ["Semana", "Mes"])

        if modo_periodo == "Semana":
            col_periodo = 'SEMANA_ANALISIS'
            periodos = sorted([int(x) for x in df[col_periodo].dropna().unique()])
            label_a, label_b = "Semana A (Base)", "Semana B (Actual)"
        else:
            col_periodo = 'MES FACTURA'
            periodos = sorted([str(x) for x in df[col_periodo].dropna().unique()])
            label_a, label_b = "Mes A (Base)", "Mes B (Actual)"

        if len(periodos) > 0:
            c_per1, c_per2 = st.sidebar.columns(2)
            per_a = c_per1.selectbox(label_a, periodos, index=0)
            per_b = c_per2.selectbox(label_b, periodos, index=min(1, len(periodos)-1))

            df_a = df[df[col_periodo] == per_a]
            df_b = df[df[col_periodo] == per_b]

            # ---------------------------------------------------------
            # TABS DE VISUALIZACIÓN Y ANÁLISIS
            # ---------------------------------------------------------
            tab1, tab2, tab3 = st.tabs(["📊 Comparativo Financiero y Medias", "🚨 Auditoría de Anomalías", "📝 Prompt para IA Executive"])

            # TAB 1: COMPARATIVO Y MEDIAS
            with tab1:
                st.subheader(f"📊 Comparativa Directa: {modo_periodo} {per_a} vs {modo_periodo} {per_b}")

                # Cálculos de Métricas
                viajes_a = len(df_a)
                viajes_b = len(df_b)

                media_viaje_a = df_a['TOTAL FLETE'].mean() if viajes_a > 0 else 0
                media_viaje_b = df_b['TOTAL FLETE'].mean() if viajes_b > 0 else 0

                tar_a = df_a['TARIMAS TOTALES POR VIAJE'].sum() if 'TARIMAS TOTALES POR VIAJE' in df_a.columns else 0
                tar_b = df_b['TARIMAS TOTALES POR VIAJE'].sum() if 'TARIMAS TOTALES POR VIAJE' in df_b.columns else 0
                tot_a = df_a['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_a.columns else 0
                tot_b = df_b['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_b.columns else 0

                costo_tarima_a = (tot_a / tar_a) if tar_a > 0 else 0
                costo_tarima_b = (tot_b / tar_b) if tar_b > 0 else 0

                km_a = df_a['KM RECORRIDOS'].sum() if 'KM RECORRIDOS' in df_a.columns else 0
                km_b = df_b['KM RECORRIDOS'].sum() if 'KM RECORRIDOS' in df_b.columns else 0
                costo_km_a = (tot_a / km_a) if km_a > 0 else 0
                costo_km_b = (tot_b / km_b) if km_b > 0 else 0

                # MOSTRAR MÉTRICAS PROMEDIO Y VOLUMÉTRICAS CLARAS (A vs B)
                st.markdown("### 📐 Resumen de Indicadores Clave (KPIs)")

                m_col1, m_col2, m_col3, m_col4 = st.columns(4)

                with m_col1:
                    st.metric(
                        label=f"Total Viajes ({modo_periodo} {per_a} ➜ {per_b})",
                        value=f"{viajes_a} ➜ {viajes_b}",
                        delta=f"{viajes_b - viajes_a} viajes"
                    )

                with m_col2:
                    var_viaje = ((media_viaje_b - media_viaje_a) / media_viaje_a * 100) if media_viaje_a > 0 else 0
                    st.metric(
                        label=f"Costo Medio/Viaje ({modo_periodo} {per_a} ➜ {per_b})",
                        value=f"${media_viaje_a:,.2f} ➜ ${media_viaje_b:,.2f}",
                        delta=f"{var_viaje:+.1f}%"
                    )

                with m_col3:
                    var_tar = ((costo_tarima_b - costo_tarima_a) / costo_tarima_a * 100) if costo_tarima_a > 0 else 0
                    st.metric(
                        label=f"Costo Medio/Tarima ({modo_periodo} {per_a} ➜ {per_b})",
                        value=f"${costo_tarima_a:,.2f} ➜ ${costo_tarima_b:,.2f}",
                        delta=f"{var_tar:+.1f}%"
                    )

                with m_col4:
                    var_km = ((costo_km_b - costo_km_a) / costo_km_a * 100) if costo_km_a > 0 else 0
                    st.metric(
                        label=f"Costo Medio/KM ({modo_periodo} {per_a} ➜ {per_b})",
                        value=f"${costo_km_a:,.2f} ➜ ${costo_km_b:,.2f}",
                        delta=f"{var_km:+.1f}%"
                    )

                st.markdown("---")
                st.markdown("### 💵 Desglose de Gastos Acumulados")

                conceptos = ['FLETE FACTURA', 'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS', 'TOTAL FLETE']
                filas = []
                for conc in conceptos:
                    m_a = df_a[conc].sum() if conc in df_a.columns else 0
                    m_b = df_b[conc].sum() if conc in df_b.columns else 0
                    dif = m_b - m_a
                    pct = ((m_b - m_a) / m_a * 100) if m_a > 0 else 0

                    filas.append({
                        'Línea de Gasto': conc,
                        f'{modo_periodo} {per_a}': f"${m_a:,.2f}",
                        f'{modo_periodo} {per_b}': f"${m_b:,.2f}",
                        'Diferencia ($)': f"${dif:,.2f}",
                        'Variación (%)': f"{pct:+.1f}%"
                    })
                st.table(pd.DataFrame(filas))

            # TAB 2: AUDITORÍA DE ANOMALÍAS
            with tab2:
                media_ref = media_viaje_a
                viajes_altos = df_b[df_b['TOTAL FLETE'] > media_ref].copy() if len(df_b) > 0 else pd.DataFrame()

                if not viajes_altos.empty:
                    viajes_altos['Diferencia vs Media Base'] = viajes_altos['TOTAL FLETE'] - media_ref
                    viajes_altos = viajes_altos.sort_values(by='TOTAL FLETE', ascending=False)

                    st.warning(f"🚨 Auditoría: **{len(viajes_altos)} viajes** en el {modo_periodo} {per_b} superan el costo promedio del {modo_periodo} {per_a} (${media_ref:,.2f})")

                    cols_detalle = [
                        'MES_ORIGEN', 'TIPO DE EMBARQUE', 'CLIENTE', 'TRANSPORTISTA',
                        'LOCALIDAD', 'TIPO DE TRANSPORTE', 'TARIMAS TOTALES POR VIAJE',
                        'KM RECORRIDOS', 'FLETE FACTURA', 'DEMORAS Y ESTADIAS',
                        'TOTAL FLETE', 'Diferencia vs Media Base'
                    ]
                    cols_existentes = [c for c in cols_detalle if c in viajes_altos.columns]
                    st.dataframe(viajes_altos[cols_existentes], use_container_width=True)
                else:
                    st.success(f"✅ No se encontraron viajes en el {modo_periodo} {per_b} que superen la media del {modo_periodo} {per_a}.")

            # TAB 3: PROMPT GENERATOR
            with tab3:
                tot_a_sum = df_a['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_a.columns else 0
                tot_b_sum = df_b['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_b.columns else 0
                var_tot = ((tot_b_sum - tot_a_sum) / tot_a_sum * 100) if tot_a_sum > 0 else 0

                prompt_texto = f"""Actúa como un Gerente Senior de Logística y Cadena de Suministro.
Analiza la siguiente variación de fletes e imprevistos financieros y genera un reporte ejecutivo.

DATOS COMPARATIVOS ({modo_periodo.upper()} {per_a} vs {modo_periodo.upper()} {per_b}):
- Periodo Base ({modo_periodo} {per_a}): Gasto Total: ${tot_a_sum:,.2f} | Costo Medio/Viaje: ${media_viaje_a:,.2f} | Costo Medio/Tarima: ${costo_tarima_a:,.2f}
- Periodo Actual ({modo_periodo} {per_b}): Gasto Total: ${tot_b_sum:,.2f} | Costo Medio/Viaje: ${media_viaje_b:,.2f} | Costo Medio/Tarima: ${costo_tarima_b:,.2f}
- Variación del Gasto Total: {var_tot:+.2f}%
- Filtro Aplicado -> Embarque: {embarque_sel} | Cliente: {clientes_sel if clientes_sel else 'Todos'} | Transportista: {transp_sel if transp_sel else 'Todos'}

ESTRUCTURA DEL REPORTE SOLICITADA:
1. 📌 Resumen Ejecutivo (2-3 oraciones clave)
2. 🚨 Alertas Operativas y Desviaciones
3. 💡 Recomendaciones de Negocio para Optimización de Costos"""

                st.code(prompt_texto, language="markdown")
        else:
            st.error("No hay suficiente información para comparar con los filtros seleccionados.")
else:
    st.info("👆 Por favor sube tu archivo Excel o CSV para comenzar el análisis.")