# -*- coding: utf-8 -*-
"""LogiSense AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQYqmqvx7QPpevgSE1ogGdNfAiXSV-eK
"""

import streamlit as st
import pandas as pd
import numpy as np

# Configuración de la página
st.set_page_config(page_title="LogiSense AI", page_icon="🚚", layout="wide")

# ==========================================
# 1. CONFIGURACIÓN DE LÍMITES Y LIMPIEZA
# ==========================================
CONFIG_HOJAS = {
    'ENERO': 430,
    'FEBRERO': 408,
    'MARZO': 370,
    'ABRIL': 662,
    'MAYO': 394,
    'JUNIO': 398,
    'JULIO': 387
}

def limpiar_y_procesar_dataframe(df_in):
    """Limpia los tipos de datos numéricos y asegura la columna de semana."""
    df_clean = df_in.copy()

    # Asignación de la semana de análisis
    col_sem = 'SEMANA CALENDARIO FACTURA' if 'SEMANA CALENDARIO FACTURA' in df_clean.columns else 'SEMANA CALENDARIO PEDIDO'
    if col_sem in df_clean.columns:
        df_clean['SEMANA_ANALISIS'] = pd.to_numeric(df_clean[col_sem], errors='coerce')
    else:
        df_clean['SEMANA_ANALISIS'] = 1

    # Columnas de costo, volumen y tarimas a limpiar
    cols_moneda = [
        'IMPORTE FACTURADO SIN IVA', 'KG MOVIDOS', 'FLETE FACTURA',
        'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS',
        'TOTAL FLETE', 'KM RECORRIDOS', 'TARIMAS TOTALES POR VIAJE',
        'COSTO POR TARIMA', 'TARIMA', 'TARIMAS'
    ]

    for col in cols_moneda:
        if col in df_clean.columns:
            s = df_clean[col].astype(str).str.replace('$', '', regex=False)\
                                         .str.replace(',', '', regex=False)\
                                         .str.replace(' ', '', regex=False)\
                                         .str.strip()
            df_clean[col] = pd.to_numeric(s, errors='coerce').fillna(0)

    return df_clean

def cargar_excel_con_limites(uploaded_file):
    """Lee cada hoja respetando los límites de filas configurados originalmente."""
    xls = pd.ExcelFile(uploaded_file)
    lista_dfs = []

    for nombre_hoja, limite_fila in CONFIG_HOJAS.items():
        if nombre_hoja in xls.sheet_names:
            # Leemos solo hasta la fila indicada en CONFIG_HOJAS
            df_hoja = pd.read_excel(uploaded_file, sheet_name=nombre_hoja, nrows=limite_fila - 1)

            # Limpiamos los encabezados de columna
            df_hoja.columns = [str(h).strip() for h in df_hoja.columns]
            df_hoja['MES_ORIGEN'] = nombre_hoja
            lista_dfs.append(df_hoja)

    if lista_dfs:
        df_consolidado = pd.concat(lista_dfs, ignore_index=True)
        return limpiar_y_procesar_dataframe(df_consolidado)
    else:
        # Si el archivo no tiene nombres de meses, lee la primera hoja completa
        df_raw = pd.read_excel(uploaded_file)
        return limpiar_y_procesar_dataframe(df_raw)

# ==========================================
# 2. INTERFAZ PRINCIPAL
# ==========================================
st.title("🚚 LogiSense AI — Analítica Logística y Fletes")

st.sidebar.header("Carga de Datos")
uploaded_file = st.sidebar.file_uploader("Sube tu archivo (Excel con pestañas de meses)", type=['xlsx', 'csv'])

df = None

if uploaded_file is not None:
    try:
        with st.spinner("⏳ Aplicando recortes de filas por mes y consolidando datos..."):
            if uploaded_file.name.endswith('.xlsx'):
                df = cargar_excel_con_limites(uploaded_file)
            else:
                df_raw = pd.read_csv(uploaded_file)
                df = limpiar_y_procesar_dataframe(df_raw)
        st.sidebar.success(f"✅ Cargados {len(df)} registros respetando límites de filas.")
    except Exception as e:
        st.sidebar.error(f"Error al procesar el archivo: {e}")

# ==========================================
# 3. MÓDULOS DE ANÁLISIS
# ==========================================
if df is not None:
    tab1, tab2, tab3, tab4 = st.tabs([
        "📊 Motor Comparativo",
        "🚨 Auditoría de Anomalías",
        "📝 Prompt Ejecutivo",
        "💬 Habla con tus Fletes"
    ])

    semanas_disponibles = sorted([int(x) for x in df['SEMANA_ANALISIS'].dropna().unique()])

    st.sidebar.subheader("Selección de Semanas")
    sem_a = st.sidebar.selectbox("Semana Base (A)", semanas_disponibles, index=0 if len(semanas_disponibles) > 0 else 0)
    sem_b = st.sidebar.selectbox("Semana Comparada (B)", semanas_disponibles, index=1 if len(semanas_disponibles) > 1 else 0)

    df_a = df[df['SEMANA_ANALISIS'] == sem_a]
    df_b = df[df['SEMANA_ANALISIS'] == sem_b]

    # TAB 1: COMPARATIVO
    with tab1:
        st.header(f"📊 Comparativo: Semana {sem_a} vs Semana {sem_b}")

        conceptos = ['FLETE FACTURA', 'MANIOBRAS', 'REPARTOS', 'DEMORAS Y ESTADIAS', 'OTROS', 'TOTAL FLETE']
        filas = []
        for conc in conceptos:
            m_a = df_a[conc].sum() if conc in df_a.columns else 0
            m_b = df_b[conc].sum() if conc in df_b.columns else 0
            dif = m_b - m_a
            pct = ((m_b - m_a) / m_a * 100) if m_a > 0 else 0
            filas.append({
                'Línea de Gasto': conc,
                f'Semana {sem_a}': f"${m_a:,.2f}",
                f'Semana {sem_b}': f"${m_b:,.2f}",
                'Diferencia ($)': f"${dif:,.2f}",
                'Variación (%)': f"{pct:+.1f}%"
            })

        st.table(pd.DataFrame(filas))

        # Indicadores volumétricos
        kg_a, kg_b = df_a['KG MOVIDOS'].sum() if 'KG MOVIDOS' in df_a.columns else 0, df_b['KG MOVIDOS'].sum() if 'KG MOVIDOS' in df_b.columns else 0
        tar_a = df_a['TARIMAS TOTALES POR VIAJE'].sum() if 'TARIMAS TOTALES POR VIAJE' in df_a.columns else 0
        tar_b = df_b['TARIMAS TOTALES POR VIAJE'].sum() if 'TARIMAS TOTALES POR VIAJE' in df_b.columns else 0
        tot_a, tot_b = df_a['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_a.columns else 0, df_b['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_b.columns else 0

        c_kg_a = (tot_a / kg_a) if kg_a > 0 else 0
        c_kg_b = (tot_b / kg_b) if kg_b > 0 else 0
        c_t_a = (tot_a / tar_a) if tar_a > 0 else 0
        c_t_b = (tot_b / tar_b) if tar_b > 0 else 0

        col1, col2 = st.columns(2)
        col1.metric("Costo / KG (Semana A ➔ B)", f"${c_kg_b:,.2f}", f"{(c_kg_b - c_kg_a):+,.2f}")
        col2.metric("Costo / Tarima (Semana A ➔ B)", f"${c_t_b:,.2f}", f"{(c_t_b - c_t_a):+,.2f}")

    # TAB 2: AUDITORÍA DE ANOMALÍAS
    with tab2:
        st.header(f"🚨 Auditoría de Anomalías: Semana {sem_b}")
        media_total_a = df_a['TOTAL FLETE'].mean() if len(df_a) > 0 else 0

        viajes_altos = df_b[df_b['TOTAL FLETE'] > media_total_a].copy()
        viajes_altos['Diferencia vs Media A'] = viajes_altos['TOTAL FLETE'] - media_total_a
        viajes_altos = viajes_altos.sort_values(by='TOTAL FLETE', ascending=False)

        st.warning(f"Se detectaron **{len(viajes_altos)} viajes** en la Semana {sem_b} que superan el promedio de la Semana {sem_a} (${media_total_a:,.2f}).")

        cols_detalle = ['MES_ORIGEN', 'CLIENTE', 'TRANSPORTISTA', 'CIUDAD DESTINO', 'FLETE FACTURA', 'DEMORAS Y ESTADIAS', 'TOTAL FLETE', 'Diferencia vs Media A']
        cols_existentes = [c for c in cols_detalle if c in viajes_altos.columns]

        if len(viajes_altos) > 0:
            st.dataframe(viajes_altos[cols_existentes].head(10))

    # TAB 3: PROMPT EJECUTIVO
    with tab3:
        st.header("📝 Generador de Prompt Ejecutivo")
        tot_a = df_a['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_a.columns else 0
        tot_b = df_b['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df_b.columns else 0
        var_tot = ((tot_b - tot_a) / tot_a * 100) if tot_a > 0 else 0
        media_a = df_a['TOTAL FLETE'].mean() if len(df_a) > 0 else 0

        viajes_altos = df_b[df_b['TOTAL FLETE'] > media_a].sort_values(by='TOTAL FLETE', ascending=False) if len(df_b) > 0 else pd.DataFrame()

        top_anomalias = []
        if len(viajes_altos) > 0:
            for _, r in viajes_altos.head(5).iterrows():
                top_anomalias.append(
                    f"- Cliente: {r.get('CLIENTE', 'N/A')}, Transportista: {r.get('TRANSPORTISTA', 'N/A')}, "
                    f"Destino: {r.get('CIUDAD DESTINO', 'N/A')}, Monto Total: ${r.get('TOTAL FLETE', 0):,.2f}, "
                    f"Demoras/Estadías: ${r.get('DEMORAS Y ESTADIAS', 0):,.2f}"
                )

        str_anomalias = "\n".join(top_anomalias) if top_anomalias else "No se detectaron viajes atípicos."

        prompt_generado = f"""Actúa como un Gerente Senior de Logística y Cadena de Suministro.
Analiza la siguiente variación semanal de fletes e imprevistos financieros y genera un reporte ejecutivo.

DATOS COMPARATIVOS:
- Periodo Base: Semana {sem_a} | Gasto Total: ${tot_a:,.2f} | Costo Promedio por Viaje: ${media_a:,.2f}
- Periodo Actual: Semana {sem_b} | Gasto Total: ${tot_b:,.2f}
- Variación del Gasto Total: {var_tot:+.2f}%

TOP VIAJES ATÍPICOS EN LA SEMANA {sem_b}:
{str_anomalias}

ESTRUCTURA DEL REPORTE SOLICITADA:
1. 📌 Resumen Ejecutivo (2-3 oraciones)
2. 🚨 Alertas Operativas
3. 💡 Recomendaciones de Negocio (2 acciones concretas)"""

        st.text_area("Copia este prompt para usarlo en ChatGPT o Gemini:", prompt_generado, height=300)

    # TAB 4: CHATBOT
    with tab4:
        st.header("💬 Asistente Conversacional de Fletes")
        if "messages" not in st.session_state:
            st.session_state.messages = [{"role": "assistant", "content": "¡Hola! Pregúntame sobre costo por tarima, demoras o total de viajes."}]

        for msg in st.session_state.messages:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])

        if user_query := st.chat_input("Escribe tu pregunta sobre la operación..."):
            st.session_state.messages.append({"role": "user", "content": user_query})
            with st.chat_message("user"):
                st.markdown(user_query)

            q = user_query.lower()

            if "tarima" in q or "costo por tarima" in q:
                col_tar = 'COSTO POR TARIMA' if 'COSTO POR TARIMA' in df.columns else 'TARIMAS TOTALES POR VIAJE'
                if col_tar in df.columns and 'TRANSPORTISTA' in df.columns:
                    agrupado = df.groupby('TRANSPORTISTA')[col_tar].mean()
                    top_t = agrupado.idxmax()
                    max_c = agrupado.max()
                    ans = f"🚛 El transportista con el costo por tarima promedio más alto es **{top_t}** con **${max_c:,.2f}**."
                else:
                    ans = "⚠️ No encontré la columna de tarimas o transportistas en el dataset."

            elif "demora" in q or "estadía" in q or "estadia" in q:
                if 'DEMORAS Y ESTADIAS' in df.columns:
                    df_d = df[df['DEMORAS Y ESTADIAS'] > 0]
                    ans = f"🚨 Se registraron **{len(df_d)} viajes con demoras**, sumando un sobrecosto de **${df_d['DEMORAS Y ESTADIAS'].sum():,.2f}**."
                else:
                    ans = "⚠️ No se encontró la columna 'DEMORAS Y ESTADIAS'."

            elif "viaje" in q or "total" in q or "cuanto" in q:
                tot_v = len(df)
                gasto_t = df['TOTAL FLETE'].sum() if 'TOTAL FLETE' in df.columns else 0
                ans = f"📊 El dataset contempla **{tot_v} viajes totales** con un gasto acumulado de **${gasto_t:,.2f}**."

            else:
                ans = "🤖 Consulta no reconocida. Prueba preguntando: *'costo por tarima'*, *'demoras'* o *'total de viajes'*."

            with st.chat_message("assistant"):
                st.markdown(ans)
            st.session_state.messages.append({"role": "assistant", "content": ans})

else:
    st.info("👈 Sube tu archivo de Excel en la barra lateral izquierda para iniciar el análisis.")